#!/usr/bin/env python

from __future__ import print_function

import sys

import lp


if __name__ == '__main__':
    _, targets, unclaimed, unclaimable = [
        a if a != '-' else '' for a in sys.argv
    ]

    available = targets + unclaimed + unclaimable
    if len(available) != 5 * 5:
        print('You provided {} letters. That is not a letterpress grid.'
              .format(len(available)))
        sys.exit(1)

    playable = lp.get_playable_words(available)

    print('\n'.join((
        '{:>2} - {}'.format(s, w)
        for w, s in
        lp.get_best_words(playable, targets, unclaimed)[:10]
    )))
